version: '3.8'

services:
  app:
    build: .
    container_name: idle-game
    ports:
      - "8080:8080"  # пробрасываем наружу
    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - app
      - frontend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/www/certbot
      --email ajratsagitov2129@gmail.com
      --agree-tos
      --no-eff-email
      -d asyagitov-idle.hostkey.in"
